language: rust

# Need to cache the whole `.cargo` directory to keep .crates.toml for
# cargo-update to work
#
cache:
  directories:
    - /home/travis/.cargo

# But don't cache the cargo registry
# and remove wasm-pack binary to avoid the installer asking confirmation for overwriting it.
#
before_cache:
  - rm -rf /home/travis/.cargo/git
  - rm -rf /home/travis/.cargo/registry
  - rm -rf /home/travis/.cargo/bin/wasm-pack


branches:
  only:
    - master
    - dev

jobs:

  include:

    - name  : linux stable check
      os    : linux
      rust  : stable
      script: cargo check

    - name  : linux nightly test everything
      os    : linux
      dist  : bionic
      rust  : nightly

      addons:
        firefox: latest
        apt:
          packages:
            - libssl-dev # for cargo-tarpaulin
            - libgtk-3-dev # needed for headless (sic) firefox https://bugzilla.mozilla.org/show_bug.cgi?id=1372998
            - libdbus-glib-1-dev # firefox

      # for wasm tests
      #
      install:
        - curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh


      script:
        - cargo test --no-default-features
        - cargo test
        - cargo test --features tokio
        - cargo test --release
        - cargo doc --no-deps --all-features

        - wasm-pack test  --firefox --headless --release
        # - wasm-pack test  --chrome  --headless --release # fails on travis, try again later.

        - wasm-pack test  --firefox --headless -- --features tokio
        # - wasm-pack test  --chrome  --headless -- --features tokio # fails on travis, try again later.

        # code coverage
        #
        - bash <(curl https://raw.githubusercontent.com/xd009642/tarpaulin/master/travis-install.sh)
        - cargo tarpaulin --features "tokio" --out Xml
        - bash <(curl -s https://codecov.io/bash)


    - os    : osx
      script:
        - cargo test


    - os    : windows
      script:
        - cargo test


